repos:
  - repo: https://github.com/betterleaks/betterleaks
    rev: v1.3.1
    hooks:
      - id: betterleaks

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.25.2
    hooks:
      - id: zizmor
